Catch any exception when trying to call "git"
Some projects (like Neutron) do import eventlet in docs/source/conf.py
. eventlet patches the subprocess module and due to that, the
submodule.CalledProcessError exception is not caught. So building the
documentation from an sdist tarball with having git installed (this
combination is common in package build envs like RDO) fails with:

subprocess.CalledProcessError: Command '['git', 'log', '-n1', \
  '--format=%ad', [...snipped...]

Change-Id: Ibff93605996855f01ba2bbe793285674b5c71d2e